### ISSUE TITLE
(Idea) Replace whisper.cpp by faster-whisper

### ISSUE THREAD

**Issue by M4TH1EU** [GRVYDEV/S.A.T.U.R.D.A.Y#19]
Hi there,

Nice project,
I tried to do something similar to this project some time ago and found faster-whisper to replace whisper.cpp.
https://github.com/guillaumekln/faster-whisper

It dramatically reduce STT duration and might be interesting for this project, I know it works in Python but I'm unsure about go.

Might want to take a look.
Have a nice day.

**Comment by vincentfretin** [comment]
Hi, I watched your YT video @GRVYDEV, your demo was quite nice.
@M4TH1EU with all the optimizations in ggml repository that also add support for some GPU and all those changes are planned to be backported to the whisper.cpp repository in a few weeks I read, you may want to measure that again later.

**Comment by GRVYDEV** [comment]
Hey @M4TH1EU there is already a STT implementation using faster-whisper here: https://github.com/GRVYDEV/S.A.T.U.R.D.A.Y/tree/main/stt/servers/faster-whisper-api 
An example of how to use it can be found here as well: https://github.com/GRVYDEV/S.A.T.U.R.D.A.Y/blob/main/client/cmd/http/main.go

**Comment by GRVYDEV** [comment]
Closed as this is already currently supported
