### ISSUE TITLE
Can I use this in Linux?

### ISSUE THREAD

**Issue by Devesh-N** [GRVYDEV/S.A.T.U.R.D.A.Y#21]
If so what are the installation commands

**Comment by GRVYDEV** [comment]
Yep!

1) Ensure you have these dependencies.
- opus 
- pkg-config 
- mecab 
- espeak 
- make
- golang
- gcc
- Python > 3.7 < 3.11

If not you should be able to get them from your package manager. 

2) Follow the instructions in the [readme](https://github.com/GRVYDEV/S.A.T.U.R.D.A.Y/tree/main#1-rtc)

**Comment by Devesh-N** [comment]
> Yep!
> 
> 1. Ensure you have these dependencies.
> 
> * opus
> * pkg-config
> * mecab
> * espeak
> * make
> * golang
> * gcc
> * Python > 3.7 < 3.11
> 
> If not you should be able to get them from your package manager.
> 
> 2. Follow the instructions in the [readme](https://github.com/GRVYDEV/S.A.T.U.R.D.A.Y/tree/main#1-rtc)

Thanks @GRVYDEV
