### ISSUE TITLE
NewRTCConnection without transcriptionStream

### ISSUE THREAD

**Issue by infinityp913** [GRVYDEV/S.A.T.U.R.D.A.Y#25]
Hi @GRVYDEV , awesome project! Thanks for the taking the time and effort for building this in public.

I wanted to test my webrtc streaming between the browser and the go client without the STT for now.
So, I wanted to pass the transcriptionStream as nil and I saw that there's a fixme about NewRTCConnection blowing up if a transcriptionStream is not passed in.  

Could you elaborate why that happens and how I could fix it? 

Right now, I get the log `...transcription relay is disabled` as expected but then get a `websocket: bad handshake` error.

**Comment by GRVYDEV** [comment]
Hey thanks for the kind words! Could you walk through the steps you are following to reproduce this error? Right now if I provide nil for transcriptionStream in the SaturdayClient everything seems to work as intended!

**Comment by infinityp913** [comment]
Hi so sorry for the super late reply! It was an error on my end, I'd used SSL cert and key for the RTC server and hence had a `wss` url but was using `ws` as the URL scheme in the `url.URL{}` line [here](https://github.com/GRVYDEV/S.A.T.U.R.D.A.Y/blob/18b40f751bb663f4d8f9fe01c58772aa59f831a4/client/cmd/whisper.cpp/main.go#L51) 

Thanks!
